import type { Metadata } from "next";
import RootNav from "./component/RootNav";
import Footer from "../shared/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <RootNav />
        {children}
      <Footer />
    </main>    
  );
}
